var routes = {}
routes.register = require("./register")
routes.login = require("./login")
routes.user = require("./user")
routes.plugins = require("./plugins")
routes.publishers = require("./publishers")
routes.logout = require("./logout")
routes.assets = require("./assets")
module.exports = routes
